name: Generate AsyncAPI HTML Docs

on:
  push:
    branches: [main]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install AsyncAPI Generator
        run: npm install -g @asyncapi/generator

      - name: Generate HTML docs
        run: |
          mkdir -p docs
          ag asyncapi.yaml @asyncapi/html-template -o docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
